### ISSUE TITLE
Store the score

### ISSUE THREAD

**Issue by kanishksh4rma** [lonewolf-X/turtlerace#1]
Wanna store the name of the winner in text file. Can anyone help plz ?

**Comment by siddhantrao23** [comment]
Hey! Wanna help you out. Not sure what you mean by name of the winner.

**Comment by kanishksh4rma** [comment]
hey @siddhantrao23 i'm glad to knw that you wanna help. 
By name of the winner, I meant which turtle won the race. Suppose red turtle won the race then, 'red turtle' should be stored in the file along with the data & time. :1st_place_medal: 
I hope you understand :+1:
